#!/bin/bash
aider --model "openai/$MODEL_QWEN3" --editor-model "openai/$MODEL_DEVSTRAL" --api-key openai=$LM_STUDIO_KEY --openai-api-base https://antonpetrov.dev/v1 --no-auto-commits --code-theme nord-darker


