source $HOME/.env

export TERM=xterm-256color

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export PATH="$HOME/.local/bin:$HOME/.config/nvim/node_modules/.bin:$PATH"

alias lvim="JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 nvim"
alias python="python3"
export TERMINFO_DIRS="~/.terminfo:/usr/share/terminfo"

export HISTCONTROL=ignoredups:erasedups  # no duplicate entries
export HISTSIZE=100000                   # big big history
export HISTFILESIZE=100000               # big big history
shopt -s histappend                      # append to history, don't overwrite it

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
