source $HOME/.env

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export PATH="$HOME/.local/bin:$HOME/.config/nvim/node_modules/.bin:$PATH"

alias lvim="JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 nvim"
